Resources:
  BookATableDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${file(./customvars.yml):DynamoDB.BookTable}
      AttributeDefinitions:
        # - 
        #   AttributeName: "BookingId"
        #   AttributeType: "S"
        - 
          AttributeName: "BookingRef"
          AttributeType: "S"
      KeySchema:
        # -
        #   AttributeName: "BookingId"
        #   KeyType: "HASH"
        - 
          AttributeName: "BookingRef"
          KeyType: "HASH" # Was RANGE before
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      Tags: 
        - 
          "Key" : "git"
          "Value" : ${file(./customvars.yml):gitrepo}
        - 
          "Key" : "app"
          "Value" : ${file(./customvars.yml):serviceName}
