Resources:
  BookATableDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${file(./customvars.yml):DynamoDB.BookTable}
      AttributeDefinitions:
        - 
          AttributeName: "BookingRef"
          AttributeType: "S"
        - 
          AttributeName: "BookingNumber"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "BookingRef"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      GlobalSecondaryIndexes:
        - IndexName: BookingNumber
          KeySchema: 
            - 
              AttributeName: "BookingNumber"
              KeyType: "HASH"
          Projection: 
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 10
      Tags: 
        - 
          "Key" : "git"
          "Value" : ${file(./customvars.yml):gitrepo}
        - 
          "Key" : "app"
          "Value" : ${file(./customvars.yml):serviceName}
