# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: srinivaspradhan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bistro-nord-backend

provider:
  name: aws
  runtime: nodejs20.x


  #  - ${file(./cognito/resources.yml)}
  #  - ${file(./dynamodb/resources.yml)}
  #  - ${file(./iam/resources.yml)}
  # - ${file(./lambda/resources.yml)}

# functions: 
#   - ${file(lambda/resources.yml)}

resources:
  Resources:
    - ${file(cognito/resources.yml)}
    - ${file(dynamodb/resources.yml)}
