name: Terraform Execution Pipeline.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose an action to execute.
        options:
        - deploy
        - remove

env:
  
  AWS_REGION : "us-east-1"

permissions:
      id-token: write
      contents: read

jobs:
  Serverless-SetupValidate:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::703866956858:role/GITHUB_OIDC_ROLE
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

  Serverless-Print:
    runs-on: ubuntu-latest
    needs: Serverless-SetupValidate
            
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Enter dir and deploy
        uses: serverless/github-action@v3.2
        with:
            args: print

  Serverless-Deploy:
    runs-on: ubuntu-latest
    needs: [ Serverless-SetupValidate, Serverless-Print ]
    if: | 
      ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || 
      ( github.event_name == 'workflow_dispatch' &&  github.event.inputs.choice == 'deploy')
            
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
            
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::703866956858:role/GITHUB_OIDC_ROLE
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Enter dir and deploy
        uses: serverless/github-action@v3.2
        with:
            args: deploy
      
      - name: Commit Serverless Changes to Repo
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
            

  Serverless-Remove:
    runs-on: ubuntu-latest
    needs: [ Serverless-SetupValidate, Serverless-Print ]
    if: | 
      ( github.event_name == 'workflow_dispatch' &&  github.event.inputs.choice == 'remove')
                        
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
                        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::703866956858:role/GITHUB_OIDC_ROLE
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
            
      - name: Enter dir and deploy
        uses: serverless/github-action@v3.2
        with:
            args: remove
            